import { useState } from "react";
import { useSubmitLoanRequestLeadCreation } from "../lib/api";

// ── Build payload — ONLY from form fields ─────────────────────────────────────
// NOTE: application_id is NOT included — it's generated by the API
// and returned in the response for new applications.
const buildPayload = (form) => ({
  application: {
    loan_amount: form.loanAmount,
    applicant_name: form.fullName,
    contact_name: form.fullName,
    mobile: form.mobile,
    email: form.email,
    purpose_of_loan: form.purposeOfLoan,
    employment_type: form.employmentType,
    terms_and_conditions: 1,
    loan_type_code: "PDL",
    type: "ENQUIRY_APPLICATION",
    apply_capacity: "PERSON",
    entity_type: "",
  },
  primary: {
    applicant_type: "PRIMARY",
    applicant_category: "PERSON",
    personal: {
      monthly_salary: Number(form.monthlySalary),
      primary_id_type: "PAN",
      primary_id_value: form.panCard,
      secondary_id_type: "AADHAR",
      secondary_id_value: form.aadharNumber,
      addresses: [
        {
          address_type: "PERSONAL_ADDRESS",
          address_line: form.completeAddress,
          city: form.city,
          state: form.state,
          pincode: form.pinCode,
          residence_type: form.addressType,
        },
      ],
      employment_type: form.employmentType,
      first_name: form.fullName,
      last_name: "",
      gender: form.gender,
      dob: form.dob, 
    },
  },
});

// ── Reusable field wrapper ────────────────────────────────────────────────────
const Field = ({ label, required, colSpan, children }) => (
  <div className={`space-y-2${colSpan ? ` md:col-span-${colSpan}` : ""}`}>
    <label className="text-sm font-semibold text-gray-700">
      {label}{required && <span className="text-red-500">*</span>}
    </label>
    {children}
  </div>
);

const cls = "w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition";

const INIT = {
  loanAmount: "", monthlySalary: "", employmentType: "",
  salaryMode: "", purposeOfLoan: "", fullName: "", email: "",
  mobile: "", dob: "", panCard: "", aadharNumber: "", gender: "",
  addressType: "", completeAddress: "", state: "", city: "", pinCode: "",
  terms: false,
};

// ── Component ─────────────────────────────────────────────────────────────────
export default function LoanForm() {
  const [form, setForm] = useState(INIT);
  const { mutate, isPending, isSuccess, isError, data, error, reset } = useSubmitLoanRequestLeadCreation();

  const set = (e) => {
    const { name, value, type, checked } = e.target;
    setForm((p) => ({ ...p, [name]: type === "checkbox" ? checked : value }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    reset();
    mutate(buildPayload(form), {
      onSuccess: () => setForm(INIT),
    });
  };

  // API returns the generated application_id in the response
  const applicationId = data?.application_id ?? data?.data?.application_id;

  return (
    <section className="py-16 bg-white">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-2xl font-bold text-center mb-8 text-gray-800">Loan Application</h2>

          {isSuccess && (
            <div className="mb-6 p-4 rounded-lg border bg-green-50 border-green-300 text-green-800 text-sm font-medium">
              Loan application submitted successfully!
              {applicationId && (
                <p className="mt-1 font-bold">Application ID: {applicationId}</p>
              )}
            </div>
          )}

          {isError && (
            <div className="mb-6 p-4 rounded-lg border bg-red-50 border-red-300 text-red-800 text-sm font-medium">
              {error?.message || "Something went wrong. Please try again."}
            </div>
          )}

          <div className="border-2 border-blue-100 rounded-xl p-8 shadow-sm">
            <form className="space-y-12" onSubmit={handleSubmit}>

              {/* Loan Details */}
              <div>
                <h3 className="text-lg font-bold mb-6 border-b border-gray-100 pb-2 text-gray-800">Loan Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <Field label="Loan Amount" required>
                    <input name="loanAmount" type="number" placeholder="Loan Amount"
                      value={form.loanAmount} onChange={set} className={cls} required />
                  </Field>
                  <Field label="Monthly Salary" required>
                    <input name="monthlySalary" type="number" placeholder="Monthly Income"
                      value={form.monthlySalary} onChange={set} className={cls} required />
                  </Field>
                  <Field label="Employment Type" required>
                    <select name="employmentType" value={form.employmentType} onChange={set} className={cls} required>
                      <option value="">Select</option>
                      <option value="salaried">Salaried</option>
                      <option value="self-employed">Self-Employed</option>
                    </select>
                  </Field>
                  <Field label="Salary Mode" required>
                    <select name="salaryMode" value={form.salaryMode} onChange={set} className={cls} required>
                      <option value="">Select Salary mode</option>
                      <option value="bank">Bank Transfer</option>
                      <option value="cash">Cash</option>
                      <option value="cheque">Cheque</option>
                    </select>
                  </Field>
                  <Field label="Purpose of Loan" required colSpan={2}>
                    <input name="purposeOfLoan" type="text" placeholder="Purpose of Loan"
                      value={form.purposeOfLoan} onChange={set} className={cls} required />
                  </Field>
                </div>
              </div>

              {/* Personal Details */}
              <div>
                <h3 className="text-lg font-bold mb-6 border-b border-gray-100 pb-2 text-gray-800">Personal Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <Field label="Full Name [As per PAN Card]" required>
                    <input name="fullName" type="text" placeholder="Full Name"
                      value={form.fullName} onChange={set} className={cls} required />
                  </Field>
                  <Field label="Email" required>
                    <input name="email" type="email" placeholder="Your Email"
                      value={form.email} onChange={set} className={cls} required />
                  </Field>
                  <Field label="Mobile Number" required>
                    <input name="mobile" type="tel" placeholder="Mobile Number"
                      value={form.mobile} onChange={set} className={cls} required />
                  </Field>
                  <Field label="Date Of Birth" required>
                    <input name="dob" type="date"
                      value={form.dob} onChange={set} className={cls} required />
                  </Field>
                  <Field label="PAN Card" required>
                    <input name="panCard" type="text" placeholder="PAN Card"
                      value={form.panCard} onChange={set} className={cls} required />
                  </Field>
                  <Field label="Aadhar Number" required>
                    <input name="aadharNumber" type="text" placeholder="Aadhar Number"
                      value={form.aadharNumber} onChange={set} className={cls} required />
                  </Field>
                  <Field label="Select Gender" required>
                    <select name="gender" value={form.gender} onChange={set} className={cls} required>
                      <option value="">Select Gender</option>
                      <option value="Male">Male</option>
                      <option value="Female">Female</option>
                      <option value="Other">Other</option>
                    </select>
                  </Field>
                  <Field label="Address Type" required>
                    <select name="addressType" value={form.addressType} onChange={set} className={cls} required>
                      <option value="">Select Type</option>
                      <option value="Owned">Owned</option>
                      <option value="Rented">Rented</option>
                    </select>
                  </Field>
                  <Field label="Complete Address" required colSpan={3}>
                    <input name="completeAddress" type="text" placeholder="Complete Address"
                      value={form.completeAddress} onChange={set} className={cls} required />
                  </Field>
                  <Field label="State" required>
                    <select name="state" value={form.state} onChange={set} className={cls} required>
                      <option value="">Select State</option>
                      <option value="DELHI">Delhi</option>
                      <option value="MAHARASHTRA">Maharashtra</option>
                      <option value="KARNATAKA">Karnataka</option>
                      <option value="TAMIL_NADU">Tamil Nadu</option>
                      <option value="UTTAR_PRADESH">Uttar Pradesh</option>
                    </select>
                  </Field>
                  <Field label="City" required>
                    <input name="city" type="text" placeholder="City"
                      value={form.city} onChange={set} className={cls} required />
                  </Field>
                  <Field label="Pin Code" required>
                    <input name="pinCode" type="text" placeholder="Pincode"
                      value={form.pinCode} onChange={set} className={cls} required />
                  </Field>
                </div>
              </div>

              {/* Terms */}
              <div className="flex items-center space-x-2">
                <input type="checkbox" id="terms" name="terms"
                  checked={form.terms} onChange={set}
                  className="w-4 h-4 accent-blue-600" required />
                <label htmlFor="terms" className="text-sm text-gray-600">
                  I agree to the Loan In Pocket{" "}
                  <span className="text-blue-600 cursor-pointer hover:underline">Terms & Conditions</span>
                  {" "}and{" "}
                  <span className="text-blue-600 cursor-pointer hover:underline">Privacy policy</span>.
                </label>
              </div>

              {/* Submit */}
              <button
                type="submit"
                disabled={isPending}
                className="bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white px-12 py-3 rounded-md font-bold text-lg transition-all shadow-lg flex items-center gap-2"
              >
                {isPending ? (
                  <>
                    <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24" fill="none">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
                    </svg>
                    Submitting…
                  </>
                ) : "Submit"}
              </button>

            </form>
          </div>
        </div>
      </div>
    </section>
  );
}
